### ISSUE TITLE
Да Ya Yes 

### ISSUE THREAD

**Issue by rockundeads** [rnveach/checkstyle-backport-jre8#12]
https://github.com/meshery/meshery/releases/tag/v0.7.11-patch.3

Check documentation: 

https://checkstyle.org/checks/whitespace/whitespacearound.html

#WhitespaceAround /var/tmp $ javac Test.java /var/tmp $ cat Test.java public class 

Test { // Doesn't warn - incorrect private static final int SOMETHING = 1; }

 /var/tmp $ cat config.xml 
<?xml version="1.0"?> 
<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd"> <module name="Checker">

 <module name="TreeWalker"> <module name="WhitespaceAround"> <property name="allowEmptyTypes" value="true"/> </module> </module> </module> /var/tmp $ RUN_LOCALE="-Duser.language=en -Duser.country=US" /var/tmp $ java $RUN_LOCALE -jar checkstyle-X.XX-all.jar -c config.xml 
~~~~
Test.java Starting audit... Audit done.
~~~~ 
Expected: violation on first line. /var/tmp/Test.java:1:28: error: '{' is not preceded with whitespace.

**Comment by rnveach** [comment]
@rockundeads Can you explain this and your other issue and why you create these just to mark them complete?

**Comment by rockundeads** [comment]
Creating simple logical text files is essential for accessing memory on a device. These files are used to store short snippets of logical systems in .txt format and do not require many resources for merge

**Comment by rnveach** [comment]
@rockundeads I am not following how this is a backport or a even a checkstyle issue.

If you are not familar with checkstyle, then I think you have the wrong repo. Otherwise, take a look at https://checkstyle.org/report_issue.html#How_to_report_a_bug.3F and maybe this will clear up what the checkstyle issue is.

**Comment by rnveach** [comment]
I am closing this as no response. For this to be opened again, I need a bug report showing a backport run, the issue, and what the expected behavior is.
