### ISSUE TITLE
10.13.0 release state

### ISSUE THREAD

**Issue by xvik** [rnveach/checkstyle-backport-jre8#13]
Are you not releasing [10.13.0](https://checkstyle.sourceforge.io/releasenotes.html) backport due to some problems with it?

**Comment by rnveach** [comment]
In this instance I have not even started the process of creating the release commit.

Releases are handled by only myself, in my free time. Sometimes I do split the work across a few days depending on the complexity of the code to backport and if I need to consult my "expert". While sometimes I do start the process close after CS' release, sometimes I just don't feel inclined to do it immediately.

In this instance we are only on the 4th day after the release, but I will start looking into creating the release.

**Comment by xvik** [comment]
Thank you very much for your work! 

Sorry, I did not want to rush you with the release. Very badly phrased it, sorry. I tested 10.13 and observed random segfaults on ubuntu with java 11 (java 17 was ok) and I wanted to know if you have problems with it too (should have mention it initially). 

I usually update checkstyle several times in a year, so did not track all versions. But I receive all release notifications and got feeling that you always release in a couple of days, and thought you could already face problems this time.

**Comment by xvik** [comment]
> Since you mentioned Java versions, this project is a backport to JRE 8, that is the actual JRE which is targeted and users should use

No-no, I'm using backport only for java 8. 

> For your specific issues, I recommend you post it to the main repo and provide as much details as you can.

Yes, of course, I understand the difference :) I was afraid exactly about backport stability.
Spotbugs is failing randomly with segfaults for a long time, but checkstyle (and pmd) was always working without problems (so I started to worry).

> Also to mention, main repo is discussing upgrading the required Java version again. Unless a major roadblock is hit, this repo will continue to aim at 8

Bad news, but glad to hear that backport will be supported! It becomes harder and harder to keep java 8 compatiblity: too many projects moved their baseline to java 11 or even 17.

> The 10.13 release is done and should be up.

Thank you! I checked - it works without problems.
